# Generated by Django 4.2.7 on 2023-11-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='last_confirmation_code_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
