# Generated by Django 4.2.7 on 2023-12-04 10:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_documents_document_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='identification_number',
            field=models.CharField(max_length=14, unique=True, validators=[django.core.validators.MinLengthValidator(14)]),
        ),
    ]
