# Generated by Django 4.2.7 on 2023-12-05 05:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_documents_identification_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='document_number',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
        migrations.AlterField(
            model_name='documents',
            name='identification_number',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(14)]),
        ),
    ]
