# Generated by Django 4.2.7 on 2023-12-20 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_email'),
        ('users', '0005_alter_documents_document_number_and_more'),
    ]

    operations = [
    ]
