# Generated by Django 4.2.7 on 2023-11-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='currency_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
