# Generated by Django 4.2.7 on 2023-11-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccount', '0002_alter_currency_currency_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccounts',
            name='currency',
            field=models.CharField(choices=[('BYN', 'Белорусский рубль'), ('USD', 'Американский доллар'), ('RUB', 'Российский рубль'), ('EUR', 'Евро'), ('CNY', 'Китайский юань')], max_length=3),
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
