# Generated by Django 4.2.7 on 2023-11-12 18:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccount', '0003_alter_bankaccounts_currency_delete_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccounts',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)]),
        ),
    ]
