# Generated by Django 4.2.7 on 2023-11-14 10:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccount', '0007_delete_moneytransfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_account_number', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(16)])),
                ('destination_account_number', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(16)])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('recipient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_received', to='bankaccount.bankaccounts')),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_sent', to='bankaccount.bankaccounts')),
            ],
        ),
    ]
