# Generated by Django 4.2.7 on 2023-11-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccount', '0008_moneytransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneytransfer',
            name='converted_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
