# Generated by Django 4.2.7 on 2023-11-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccount', '0009_moneytransfer_converted_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneytransfer',
            name='converted_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
