# Generated by Django 4.2.7 on 2023-12-03 16:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccount', '0010_alter_moneytransfer_converted_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccounts',
            name='account_number',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(16)]),
        ),
        migrations.AlterField(
            model_name='bankaccounts',
            name='account_type',
            field=models.CharField(choices=[('checking_account', 'Текущий счет')], max_length=30),
        ),
    ]
