# Generated by Django 4.2.7 on 2023-11-18 22:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_number', models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(16)])),
                ('issue_amount', models.DecimalField(decimal_places=0, max_digits=6)),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remainder', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_amount_per_month', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency_loan', models.CharField(choices=[('BYN', 'Белорусский рубль'), ('USD', 'Американский доллар'), ('EUR', 'Евро')], max_length=3)),
                ('date_of_start', models.DateField(auto_now_add=True)),
                ('date_of_end', models.DateField()),
                ('loan_type', models.CharField(choices=[('Consumer_loan', 'Потребительский кредит'), ('Mortgage_loan', 'Ипотечный кредиты'), ('Auto_loan', 'Автокредит')], max_length=100)),
                ('status', models.CharField(max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Loan_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_number', models.CharField(max_length=20)),
                ('summ_of_payment', models.DecimalField(decimal_places=2, max_digits=8)),
                ('remainder', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=20)),
                ('date_of_payment', models.DateField()),
                ('status', models.CharField(max_length=15)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.loans')),
            ],
        ),
    ]
