# Generated by Django 4.2.7 on 2023-11-18 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='months',
            field=models.IntegerField(null=True),
        ),
    ]
