# Generated by Django 4.2.7 on 2023-11-18 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loans_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='destination_account_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
