# Generated by Django 4.2.7 on 2023-12-04 06:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_alter_loans_loan_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans',
            name='loan_number',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(16)]),
        ),
    ]
